package com.splashcode.aqs.data.database.model;

import com.google.gson.annotations.SerializedName;
import com.j256.ormlite.field.DatabaseField;
import com.splashcode.aqs.data.database.DatabaseObject;
import com.splashcode.aqs.data.http.response.AddressResponse;

/**
 * A simple demonstration user object we are creating and persisting to the database.
 */
public class UserDatabaseObject implements DatabaseObject {

    // id is generated by the database and set on the object automatically
    @DatabaseField(generatedId = true)
    public int id;

    //User filed
    @DatabaseField(index = true)
    public String userName;
    @DatabaseField
    public String userPhone;
    @DatabaseField
    public String userEmail;

    //Address filed
    @DatabaseField
    public String streetName;
    @DatabaseField
    public String addressExtension;
    @DatabaseField
    public String zipcode;
    @DatabaseField
    public String cityName;
    @DatabaseField
    public String latitude;
    @DatabaseField
    public String longitude;

    //Company filed
    @DatabaseField
    public String companyName;
    @DatabaseField
    public String companyCatchPhrase;
    @DatabaseField
    public String companyBaseLine;

    public UserDatabaseObject() {
        // needed by ormlite
    }

    @Override
    public int getId() {
        return id;
    }
}